FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build -- --configuration=production

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist/AntiFraudeEngine ./dist/AntiFraudeEngine

ENV PORT=80
EXPOSE 80

CMD ["node", "dist/AntiFraudeEngine/server/server.mjs"]